ivw_integration_amp.settings:
  type: mapping
  label: 'IVW Settings (AMP)'
  mapping:
    amp_analytics_infonline_domain:
      type: string
      label: Domain for loading amp-analytics-infonline.html
